@startuml
 start
 if(condition A) then (yes)
 :Text 1;
 else if(condition B) (yes)
 :Text 2;
 stop
 else if(condition C) (yes)
 :Text 3;
 else if(condition 4) (yes)
 :Text 4;
 else  (nothing)
 :Text 5 ;
 endif
 stop



@enduml