@startuml

具体业务 ---> [依赖]  业务仓库

业务仓库 ---> [依赖] 本地业务实现类

业务仓库 ---> [依赖] 远程业务实现类

本地业务实现类 ---> [实现] 业务接口

远程业务实现类 --->  [实现] 业务接口

远程业务实现类 ---> [依赖] 网络请求

网络请求 --> [依赖] 网络驱动

网络驱动 --> [依赖] 网络接口

@enduml