@startuml

skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

Alice -> Bob: Authentication Request
activate Bob
Bob --> Alice: Authentication Response
deactivate Bob

Alice -> Bob: Another authentication Request
activate Bob

create Client
Bob -> Client : cx
activate Client
Client -> Bob : dsfa
destroy Client
Alice <-- Bob: another authentication Response
deactivate Bob

||34||

@enduml